---
version: '3.7'
services:
  bbugyi200.tmux_utils:
    build:
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/tmux_utils:delegated
    working_dir: /tmux_utils
    environment:
      - BETTER_EXCEPTIONS
      - CC_REPO_URL
