#!/bin/bash

###################################################################################################
#  Initializes and Starts Prime (secondary) Tmux Session                                          #
###################################################################################################

# shellcheck disable=SC2154

# ---------- Modules ----------
eval "$(shlib)"

# ---------- CLI Arguments ----------
socket_name="$1"; shift

# ---------- Global Variables ----------
# shellcheck disable=SC2154,SC2034
USAGE="usage: ${SCRIPTNAME} SOCKET_NAME [SESSION_NAME]"

if [[ -n "$1" ]]; then
    session_name="$1"; shift
else
    session_name="$(tm-session-name default)"
fi

# ---------- Main ----------
generate_prime_mux_session "${session_name}" "${socket_name}"
tm-session-root --put "${session_name}\`" "$(tm-session-root --get "${session_name}")"
(sleep 2 && tmux -L tmux_primes set status-bg red && tmux -L tmux_primes set status-fg white) &
tm "${session_name}\`"
