#!/bin/bash

###############################################################################
#  Initialize Default Tmuxinator Session on a Remote Machine
###############################################################################

eval "$(shlib)"

function run() {
    local host="$1"
    shift

    local fqdn="$1"
    shift

    local port="${1:-22}"
    shift

    {
        sleep 0.2
        wtitle zsh:"${host}"
        fullscreen
    } &

    alacritty -e ssh -p "${port}" bryan@"${fqdn}" -t tm Terminal &
}

if [[ "${SCRIPTNAME}" == "$(basename "${BASH_SOURCE[0]}")" ]]; then
    run "$@"
fi
