#!/bin/bash

################################
#  Displays Tmux Session Name  #
################################

# ---------- Modules ----------
source bugyi.sh

# ---------- Main ----------
if [[ -n "$1" ]]; then
    socket_name="$1"; shift
else
    socket_name="$(tm-socket)"
fi

# shellcheck disable=SC2016
tmux -L "${socket_name}" display-message -p "#S" | sed 's/`/\\`/g'
